theme: jekyll-theme-minimal
title: James Richardson
avatar: https://jamesgrich.github.io/assets/img/image_6483441.JPG
description: 
- Hello! 
- I'm James and i'm a Software Developer located in Norwich, UK.
- ðŸ’¼ Naked Wines
- Certification:
ðŸ§¾ Java Programming - University of Helsinki
ðŸ§¾ Learn Spring - Baeldung 
